## LOG CHANGE

### rAmCharts 1.1.3 (based on [amcharts][amcharts_url] version **3.17.3**)

  * fix init and rendered event with shiny

### rAmCharts 1.1.2 (based on [amcharts][amcharts_url] version **3.17.2**)
  
  * argument type in `amChartsOutput` is required only when `type = drill`
  * call to `plot` in shiny no longer necessary
  * better management of dependencies (dynamic loading in __R__)
  
[amcharts_url]: http://www.amcharts.com

---
---

### rAmCharts 1.1.1
  
  * Create a generic method for renderAmCharts (shiny use)
  * Create a show method for class AmChart (now plot the object if type is set)
  * fix bug in dependencies for html_document
  * Clean import when creating widget (plot method)
  * fix bug using renderAmChart with input/reactive values
  * rename renderAmChart -> renderAmCharts
  * rename amChartOutput -> amChartsOutput
  * add listeners on legend
  * new function 'runShinyExamples'
  * access the documentation with the functions api() or api(class = [className])
  
---
---
